ci:
  platform:
    NPM:
      # We use an older version that doesn't use ES6+ features to support back to node 0.10
      eslint:
        tests:
          outdated: skip
      # We use an older version that doesn't use ES6+ features to support back to node 0.10
      expect:
        tests:
          outdated: skip
      # We use an older version that doesn't use ES6+ features to support back to node 0.10
      mocha:
        tests:
          outdated: skip
